### ISSUE TITLE
OperationalError Linux

### ISSUE THREAD

**Issue by franfram** [PrefectHQ/marvin#204]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

Hello!

I installed marvin with `pip install marvin` (without a conda environment) on pop os 22.04. I'm getting the following error when running `marvin chat`: 

```
OperationalError: (sqlite3.OperationalError) no such column: bot_config.created_at
[SQL: SELECT bot_config.created_at, bot_config.updated_at, bot_config.plugins, 
bot_config.input_transformers, bot_config.id, bot_config.name, bot_config.personality, 
bot_config.instructions, bot_config.instructions_template, bot_config.description, 
bot_config.profile_picture 
FROM bot_config 
WHERE bot_config.name = ?
 LIMIT ? OFFSET ?]
[parameters: ('Marvin', 1, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

```

Any idea how to fix this?

Cheers

### Reproduction

```python3
In pop os 22.04, run: 


pip install marvin
marvin chat
```
```


### Error

```python3
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                           │
│ /home/arnle/miniconda3/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.p │
│ y:100 in execute                                                                          │
│                                                                                           │
│    97 │   │   │   else:                                                                   │
│    98 │   │   │   │   self._cursor = _cursor                                              │
│    99 │   │   except Exception as error:                                                  │
│ ❱ 100 │   │   │   self._adapt_connection._handle_exception(error)                         │
│   101 │                                                                                   │
│   102 │   def executemany(self, operation, seq_of_parameters):                            │
│   103 │   │   try:                                                                        │
│                                                                                           │
│ ╭─────────────────────────────────────── locals ────────────────────────────────────────╮ │
│ │    _cursor = <aiosqlite.cursor.Cursor object at 0x7fc0812df730>                       │ │
│ │  operation = 'SELECT bot_config.created_at, bot_config.updated_at,                    │ │
│ │              bot_config.plugins, bot_con'+251                                         │ │
│ │ parameters = ('Marvin', 1, 0)                                                         │ │
│ │       self = <sqlalchemy.dialects.sqlite.aiosqlite.AsyncAdapt_aiosqlite_cursor object │ │
│ │              at 0x7fc081312dc0>                                                       │ │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                           │
│ /home/arnle/miniconda3/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.p │
│ y:228 in _handle_exception                                                                │
│                                                                                           │
│   225 │   │   │   │   from_=error,                                                        │
│   226 │   │   │   )                                                                       │
│   227 │   │   else:                                                                       │
│ ❱ 228 │   │   │   raise error                                                             │
│   229                                                                                     │
│   230                                                                                     │
│   231 class AsyncAdaptFallback_aiosqlite_connection(AsyncAdapt_aiosqlite_connection):     │
│                                                                                           │
│ ╭────────────────────────────────────── locals ──────────────────────────────────────╮    │
│ │ error = OperationalError('no such column: bot_config.created_at')                  │    │
│ │  self = <AdaptedConnection <Connection(Thread-6, started daemon 140464776869440)>> │    │
│ ╰────────────────────────────────────────────────────────────────────────────────────╯    │
│                                                                                           │
│ /home/arnle/miniconda3/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.p │
│ y:82 in execute                                                                           │
│                                                                                           │
│    79 │   │   │   if parameters is None:                                                  │
│    80 │   │   │   │   self.await_(_cursor.execute(operation))                             │
│    81 │   │   │   else:                                                                   │
│ ❱  82 │   │   │   │   self.await_(_cursor.execute(operation, parameters))                 │
│    83 │   │   │                                                                           │
│    84 │   │   │   if _cursor.description:                                                 │
│    85 │   │   │   │   self.description = _cursor.description                              │
│                                                                                           │
│ ╭─────────────────────────────────────── locals ────────────────────────────────────────╮ │
│ │    _cursor = <aiosqlite.cursor.Cursor object at 0x7fc0812df730>                       │ │
│ │  operation = 'SELECT bot_config.created_at, bot_config.updated_at,                    │ │
│ │              bot_config.plugins, bot_con'+251                                         │ │
│ │ parameters = ('Marvin', 1, 0)                                                         │ │
│ │       self = <sqlalchemy.dialects.sqlite.aiosqlite.AsyncAdapt_aiosqlite_cursor object │ │
│ │              at 0x7fc081312dc0>                                                       │ │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                           │
│ /home/arnle/miniconda3/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py:6 │
│ 8 in await_only                                                                           │
│                                                                                           │
│    65 │   # a coroutine to run. Once the awaitable is done, the driver greenlet           │
│    66 │   # switches back to this greenlet with the result of awaitable that is           │
│    67 │   # then returned to the caller (or raised as error)                              │
│ ❱  68 │   return current.driver.switch(awaitable)                                         │
│    69                                                                                     │
│    70                                                                                     │
│    71 def await_fallback(awaitable: Coroutine) -> Any:                                    │
│                                                                                           │
│ ╭────────────────────────────────────── locals ──────────────────────────────────────╮    │
│ │ awaitable = <coroutine object Cursor.execute at 0x7fc08138ad40>                    │    │
│ │   current = <_AsyncIoGreenlet object at 0x7fc08126d2c0 (otid=0x7fc0a6d45330) dead> │    │
│ ╰────────────────────────────────────────────────────────────────────────────────────╯    │
│                                                                                           │
│ /home/arnle/miniconda3/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py:1 │
│ 21 in greenlet_spawn                                                                      │
│                                                                                           │
│   118 │   │   │   try:                                                                    │
│   119 │   │   │   │   # wait for a coroutine from await_only and then return its          │
│   120 │   │   │   │   # result back to it.                                                │
│ ❱ 121 │   │   │   │   value = await result                                                │
│   122 │   │   │   except BaseException:                                                   │
│   123 │   │   │   │   # this allows an exception to be raised within                      │
│   124 │   │   │   │   # the moderated greenlet so that it can continue                    │
│                                                                                           │
│ ╭─────────────────────────────────────── locals ────────────────────────────────────────╮ │
│ │  _require_await = False                                                               │ │
│ │            args = (<sqlalchemy.sql.selectable.Select object at 0x7fc081bf5c70>,)      │ │
│ │         context = <_AsyncIoGreenlet object at 0x7fc08126d2c0 (otid=0x7fc0a6d45330)    │ │
│ │                   dead>                                                               │ │
│ │              fn = <bound method Session.execute of <sqlmodel.orm.session.Session      │ │
│ │                   object at 0x7fc081c7fa90>>                                          │ │
│ │          kwargs = {                                                                   │ │
│ │                   │   'params': None,                                                 │ │
│ │                   │   'execution_options': immutabledict({'prebuffer_rows': True}),   │ │
│ │                   │   'bind_arguments': None                                          │ │
│ │                   }                                                                   │ │
│ │          result = <coroutine object Cursor.execute at 0x7fc08138ad40>                 │ │
│ │ switch_occurred = True                                                                │ │
│ │           value = <aiosqlite.cursor.Cursor object at 0x7fc0812df730>                  │ │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                           │
│ /home/arnle/miniconda3/lib/python3.9/site-packages/aiosqlite/cursor.py:37 in execute      │
│                                                                                           │
│    34 │   │   """Execute the given query."""                                              │
│    35 │   │   if parameters is None:                                                      │
│    36 │   │   │   parameters = []                                                         │
│ ❱  37 │   │   await self._execute(self._cursor.execute, sql, parameters)                  │
│    38 │   │   return self                                                                 │
│    39 │                                                                                   │
│    40 │   async def executemany(                                                          │
│                                                                                           │
│ ╭─────────────────────────────────────── locals ────────────────────────────────────────╮ │
│ │ parameters = ('Marvin', 1, 0)                                                         │ │
│ │       self = <aiosqlite.cursor.Cursor object at 0x7fc0812df730>                       │ │
│ │        sql = 'SELECT bot_config.created_at, bot_config.updated_at,                    │ │
│ │              bot_config.plugins, bot_con'+251                                         │ │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                           │
│ /home/arnle/miniconda3/lib/python3.9/site-packages/aiosqlite/cursor.py:31 in _execute     │
│                                                                                           │
│    28 │                                                                                   │
│    29 │   async def _execute(self, fn, *args, **kwargs):                                  │
│    30 │   │   """Execute the given function on the shared connection's thread."""         │
│ ❱  31 │   │   return await self._conn._execute(fn, *args, **kwargs)                       │
│    32 │                                                                                   │
│    33 │   async def execute(self, sql: str, parameters: Iterable[Any] = None) -> "Cursor" │
│    34 │   │   """Execute the given query."""                                              │
│                                                                                           │
│ ╭─────────────────────────────────────── locals ────────────────────────────────────────╮ │
│ │   args = (                                                                            │ │
│ │          │   'SELECT bot_config.created_at, bot_config.updated_at,                    │ │
│ │          bot_config.plugins, bot_con'+251,                                            │ │
│ │          │   ('Marvin', 1, 0)                                                         │ │
│ │          )                                                                            │ │
│ │     fn = <built-in method execute of sqlite3.Cursor object at 0x7fc08137d180>         │ │
│ │ kwargs = {}                                                                           │ │
│ │   self = <aiosqlite.cursor.Cursor object at 0x7fc0812df730>                           │ │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                           │
│ /home/arnle/miniconda3/lib/python3.9/site-packages/aiosqlite/core.py:137 in _execute      │
│                                                                                           │
│   134 │   │                                                                               │
│   135 │   │   self._tx.put_nowait((future, function))                                     │
│   136 │   │                                                                               │
│ ❱ 137 │   │   return await future                                                         │
│   138 │                                                                                   │
│   139 │   async def _connect(self) -> "Connection":                                       │
│   140 │   │   """Connect to the actual sqlite database."""                                │
│                                                                                           │
│ ╭─────────────────────────────────────── locals ────────────────────────────────────────╮ │
│ │     args = (                                                                          │ │
│ │            │   'SELECT bot_config.created_at, bot_config.updated_at,                  │ │
│ │            bot_config.plugins, bot_con'+251,                                          │ │
│ │            │   ('Marvin', 1, 0)                                                       │ │
│ │            )                                                                          │ │
│ │       fn = <built-in method execute of sqlite3.Cursor object at 0x7fc08137d180>       │ │
│ │ function = functools.partial(<built-in method execute of sqlite3.Cursor object at     │ │
│ │            0x7fc08137d180>, 'SELECT bot_config.created_at, bot_config.updated_at,     │ │
│ │            bot_config.plugins, bot_config.input_transformers, bot_config.id,          │ │
│ │            bot_config.name, bot_config.personality, bot_config.instructions,          │ │
│ │            bot_config.instructions_template, bot_config.description,                  │ │
│ │            bot_config.profile_picture \nFROM bot_config \nWHERE bot_config.name = ?\n │ │
│ │            LIMIT ? OFFSET ?', ('Marvin', 1, 0))                                       │ │
│ │   future = <Future finished exception=OperationalError('no such column:               │ │
│ │            bot_config.created_at')>                                                   │ │
│ │   kwargs = {}                                                                         │ │
│ │     self = <Connection(Thread-6, started daemon 140464776869440)>                     │ │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                           │
│ /home/arnle/miniconda3/lib/python3.9/asyncio/futures.py:284 in __await__                  │
│                                                                                           │
│   281 │   def __await__(self):                                                            │
│   282 │   │   if not self.done():                                                         │
│   283 │   │   │   self._asyncio_future_blocking = True                                    │
│ ❱ 284 │   │   │   yield self  # This tells Task to wait for completion.                   │
│   285 │   │   if not self.done():                                                         │
│   286 │   │   │   raise RuntimeError("await wasn't used with future")                     │
│   287 │   │   return self.result()  # May raise too.                                      │
│                                                                                           │
│ ╭─────────────────────────────────────── locals ────────────────────────────────────────╮ │
│ │ self = <Future finished exception=OperationalError('no such column:                   │ │
│ │        bot_config.created_at')>                                                       │ │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                           │
│ /home/arnle/miniconda3/lib/python3.9/asyncio/tasks.py:328 in __wakeup                     │
│                                                                                           │
│   325 │                                                                                   │
│   326 │   def __wakeup(self, future):                                                     │
│   327 │   │   try:                                                                        │
│ ❱ 328 │   │   │   future.result()                                                         │
│   329 │   │   except BaseException as exc:                                                │
│   330 │   │   │   # This may also be a cancellation.                                      │
│   331 │   │   │   self.__step(exc)                                                        │
│                                                                                           │
│ ╭─────────────────────────────────────── locals ────────────────────────────────────────╮ │
│ │ future = <Future finished exception=OperationalError('no such column:                 │ │
│ │          bot_config.created_at')>                                                     │ │
│ │   self = None                                                                         │ │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                           │
│ /home/arnle/miniconda3/lib/python3.9/asyncio/futures.py:201 in result                     │
│                                                                                           │
│   198 │   │   │   raise exceptions.InvalidStateError('Result is not ready.')              │
│   199 │   │   self.__log_traceback = False                                                │
│   200 │   │   if self._exception is not None:                                             │
│ ❱ 201 │   │   │   raise self._exception                                                   │
│   202 │   │   return self._result                                                         │
│   203 │                                                                                   │
│   204 │   def exception(self):                                                            │
│                                                                                           │
│ ╭─────────────────────────────────────── locals ────────────────────────────────────────╮ │
│ │ self = <Future finished exception=OperationalError('no such column:                   │ │
│ │        bot_config.created_at')>                                                       │ │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                           │
│ /home/arnle/miniconda3/lib/python3.9/site-packages/aiosqlite/core.py:110 in run           │
│                                                                                           │
│   107 │   │   │   │   break                                                               │
│   108 │   │   │   try:                                                                    │
│   109 │   │   │   │   LOG.debug("executing %s", function)                                 │
│ ❱ 110 │   │   │   │   result = function()                                                 │
│   111 │   │   │   │   LOG.debug("operation %s completed", function)                       │
│   112 │   │   │   │                                                                       │
│   113 │   │   │   │   def set_result(fut, result):                                        │
│                                                                                           │
│ ╭─────────────────────────────────────── locals ────────────────────────────────────────╮ │
│ │      function = functools.partial(<built-in method close of sqlite3.Connection object │ │
│ │                 at 0x7fc081ca56c0>)                                                   │ │
│ │        future = <Future finished result=None>                                         │ │
│ │        result = None                                                                  │ │
│ │          self = <Connection(Thread-6, started daemon 140464776869440)>                │ │
│ │ set_exception = <function Connection.run.<locals>.set_exception at 0x7fc08128b430>    │ │
│ │    set_result = <function Connection.run.<locals>.set_result at 0x7fc08128b0d0>       │ │
│ ╰───────────────────────────────────────────────────────────────────────────────────────╯ │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
OperationalError: (sqlite3.OperationalError) no such column: bot_config.created_at
[SQL: SELECT bot_config.created_at, bot_config.updated_at, bot_config.plugins, 
bot_config.input_transformers, bot_config.id, bot_config.name, bot_config.personality, 
bot_config.instructions, bot_config.instructions_template, bot_config.description, 
bot_config.profile_picture 
FROM bot_config 
WHERE bot_config.name = ?
 LIMIT ? OFFSET ?]
[parameters: ('Marvin', 1, 0)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

```
```


### Versions

```Text
Same error when running `marvin version`
```

### Additional context

Pop OS 22.04

**Comment by zzstoatzz** [comment]
hi @franfram - this appears to be the same issue as #195 (cc @jlowin)

if you don't have any data saved, then `rm ~/.marvin/marvin.sqlite && marvin database reset -y` should solve this - but thanks for raising! this is something we need to fix

**Comment by franfram** [comment]
Hello @zzstoatzz, thanks for replying!

I tried running `rm ~/.marvin/marvin.sqlite && marvin database reset -y` but it did not solve the issue. When running that command, I get the following error: 

```
ERROR [marvin.bots] Failed to install bots
Traceback (most recent call last):
  File "/home/arnle/miniconda3/lib/python3.9/site-packages/marvin/bots/__init__.py", line 16, in install_bots
    await bot.save(if_exists="update")
  File "/home/arnle/miniconda3/lib/python3.9/site-packages/marvin/bot/base.py", line 276, in save
    bot_config = self.to_bot_config()
  File "/home/arnle/miniconda3/lib/python3.9/site-packages/marvin/bot/base.py", line 235, in to_bot_config
    return BotConfig(
  File "<string>", line 4, in __init__
  File "/home/arnle/miniconda3/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 482, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/home/arnle/miniconda3/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/arnle/miniconda3/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/arnle/miniconda3/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/home/arnle/miniconda3/lib/python3.9/site-packages/sqlmodel/main.py", line 498, in __init__
    values, fields_set, validation_error = validate_model(
  File "pydantic/main.py", line 1076, in pydantic.main.validate_model
  File "pydantic/fields.py", line 884, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1101, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 1148, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 318, in pydantic.class_validators._generic_validator_basic.lambda13
  File "pydantic/types.py", line 433, in pydantic.types.ConstrainedStr.validate
AttributeError: 'str' object has no attribute 'match'

```

Cheers!
